In [2]:
# Hotelling's T² One-Sample Test (manual step-by-step)
# ---------------------------------------------------

import numpy as np
import pandas as pd
from scipy import stats

# === 1. Load dataset ===
# Ganti dengan path dataset Anda
file_path = "C:/Uner/Semester 5/Multivariat/Coolyeah/Data_TM3.xlsx"
df = pd.read_excel(file_path)

In [3]:
# Pilih kolom numerik
df_num = df.select_dtypes(include=[np.number])
print("Kolom numerik yang digunakan:", df_num.columns.tolist())

Kolom numerik yang digunakan: ['Y1', 'Y2', 'Y3']


In [4]:
# === 2. Basic dimensions ===
X = df_num.values
n, p = X.shape
print(f"Jumlah sampel (n) = {n}, Jumlah variabel (p) = {p}\n")

Jumlah sampel (n) = 52, Jumlah variabel (p) = 3



In [5]:
# === 3. Sample mean vector ===
xbar = X.mean(axis=0)
print("Vektor rata-rata sampel (x̄):")
print(xbar, "\n")

Vektor rata-rata sampel (x̄):
[56.71288462 50.64365385 53.61653846] 



In [6]:
# === 4. Deviation matrix dan sample covariance matrix ===
D = X - xbar
S = (D.T @ D) / (n - 1)
print("Matriks kovarians sampel (S):")
print(S, "\n")

Matriks kovarians sampel (S):
[[ 905.17273073 1088.85363043 1137.99228861]
 [1088.85363043 1328.27800796 1406.71513643]
 [1137.99228861 1406.71513643 1537.84191327]] 



In [7]:
# === 5. Inverse of S ===
try:
    S_inv = np.linalg.inv(S)
    print("S dapat diinvers.\n")
except np.linalg.LinAlgError:
    S_inv = np.linalg.pinv(S)
    print("S singular, gunakan pseudo-inverse.\n")

print("S⁻¹ =")
print(S_inv, "\n")

S dapat diinvers.

S⁻¹ =
[[ 0.12813083 -0.1478413   0.04041943]
 [-0.1478413   0.19467508 -0.06867423]
 [ 0.04041943 -0.06867423  0.03355877]] 



In [8]:
# === 6. Tentukan μ0 (hipotesis mean) ===
# Ganti dengan nilai hipotesis yang sesuai
mu0 = np.zeros(p)  
alpha = 0.05

print("Hipotesis mean (μ0):", mu0, "\n")

Hipotesis mean (μ0): [0. 0. 0.] 



In [9]:
# === 7. Hitung T² ===
d = xbar - mu0
T2 = float(n * (d.T @ S_inv @ d))
print(f"T² = {T2:.6f}\n")

T² = 1638.211903



In [10]:
# === 8. Konversi ke F-statistic ===
F_stat = (n - p) / ((n - 1) * p) * T2
df1, df2 = p, n - p
p_value = stats.f.sf(F_stat, df1, df2)

print(f"F-statistic = {F_stat:.6f}")
print(f"Derajat bebas: df1 = {df1}, df2 = {df2}")
print(f"p-value = {p_value:.6e}\n")

F-statistic = 524.656100
Derajat bebas: df1 = 3, df2 = 49
p-value = 3.194569e-37



In [11]:
# === 9. Nilai kritis ===
F_crit = stats.f.ppf(1 - alpha, df1, df2)
T2_crit = ((n - 1) * p) / (n - p) * F_crit

print(f"F kritis (α={alpha}) = {F_crit:.6f}")
print(f"T² kritis = {T2_crit:.6f}\n")

F kritis (α=0.05) = 2.793949
T² kritis = 8.723963



In [12]:
# === 10. Keputusan ===
if T2 > T2_crit:
    print("Keputusan: Tolak H0")
else:
    print("Keputusan: Gagal tolak H0")

Keputusan: Tolak H0
